'''
Created on 6 oct. 2017

@author: briofons@gmail.com

This is a basic parser for scrapping and get 
information about
page generated by known CMS

TODO JOOMLA, WORDPRESS, ...
'''

from lxml import html
import requests

class Parser:
    
    tree_page = ""
    
    def __init__(self, url):
        self.page = url
        
        
    def doParse(self, url_page):
        page = requests.get(url_page)
        tree_page = html.fromstring(page.content)
        metaInf = tree_page.xpath('/html/head/meta[@name="generator"]/@content')
        path = "".join(metaInf)
        
        if path.find("Joomla") is not -1:
            return True
        else:    
            return False
    
        
            

        








